BookMates/urls.py
from django.contrib import admin
from django.urls import path, include
from LoginRegister import views
urlpatterns = [
    path('', include('LoginRegister.urls')),
    path('', views.show_home, name='home'),
    path('admin/', admin.site.urls),
    path('editbuku/', include('MengelolaBuku.urls')),
    path('searchbuku/', include('SearchKatalog.urls')),
    path('challenge/', include('ChallengeLeaderboard.urls')),
    path('',include('Dashboard.urls')),
    path('',include('Komunitas.urls')),
    path('leaderboard/', include('ReviewerLeaderboard.urls')),
    path('auth/', include('authentication.urls')),
    # path('api/books/', include("book.urls"))
]

LoginRegister/urls.py
from django.urls import path
from .views import show_home, user_login, user_register, user_logout
app_name = 'LoginRegister'

urlpatterns = [
    path('', show_home, name='show_home'),
    path('register/', user_register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

LoginRegister/models.py
from django.db import models
from django.contrib.auth.models import User
from MengelolaBuku.models import Pengguna

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    isGuru = models.BooleanField()

LoginRegister/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User  # Import User model
from MengelolaBuku.models import Pengguna

class RegistrationForm(UserCreationForm):
    is_teacher = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})
    )

    class Meta:
        model = User  # Use the built-in User model
        fields = ["username", "password1", "password2"]

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        if commit:
            user.save()
        # Create a related Pengguna instance
        Pengguna.objects.create(user=user, isGuru=self.cleaned_data['is_teacher'], point=0)
        return user

LoginRegister/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from Dashboard.views import show_main
from MengelolaBuku.models import Pengguna

# Create your views here.
def show_xml(request):
    data = Pengguna.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Pengguna.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Pengguna.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Pengguna.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_home(request):
    return render(request, 'home.html')

def user_register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        isGuru = request.POST.get('isGuru')
        if form.is_valid():
            new_user = form.save()
            isGuru = request.POST.get('isGuru') == 'on'
            Pengguna.objects.create(user=new_user, isGuru=isGuru, point=0).save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('LoginRegister:show_home')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f'{field}: {error}')
    else:
        form = RegistrationForm()
    
    context = {'form': form}
    return render(request, 'register.html', context)

def user_login(request):
    if request.method == 'POST':
        print('Welcome')
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Create or get the Pengguna instance for the logged-in user
            created = Pengguna.objects.get_or_create(user=user, defaults={'isGuru': False, 'point': 0})
             # Additional logic if needed based on whether the instance was created or not
            if created:
                messages.success(request, 'Welcome! Your Pengguna instance has been created.')
            else:
                messages.success(request, 'Welcome back!')
            response = HttpResponseRedirect(reverse("Dashboard:show_main"))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/login')
def user_logout(request):
    logout(request)
    response = HttpResponseRedirect(reverse('LoginRegister:show_home'))
    return response 

LoginRegister/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
          background: url("{% static 'home_bg.jpg' %}");
          background-repeat: no-repeat;
          background-size: cover;
        }

        .box {
          background-color: #FAEECE;
          border-radius: 8px;
          box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
          width: 90%;
          margin: 0 auto;
          padding: 10px;
          color: #fff; /* White text color */
        }
        
        .btn-primary {
          background-color: #FF6B6C;
          border-color: #FF5050;
          color: #fff;
          font-family: 'Kavoon';
          padding: 25px 60px;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
        }

        .register-link {
          color: #fff; 
          font-weight: bold;
          margin-top: 20px;
        }

        .register-link a {
          color: #D2BA18;
          text-decoration: none;
        }
    </style>
</head>
<body>
  <div class="container-fluid px-0">
    <div class="row">
        <div class="col">
            <!-- Kolom kiri -->
            <h2 style="color: #60AB9A; font-family: 'Kavoon'; font-weight: bold; font-size: 50px; padding: 20px; margin-top:50px; margin-left:30px;">Hi There!</h2>
        </div>
        <div class="col">
            <!-- Kolom kanan -->
          <div class="text-center">
              <div class="box">
                  <div class="row justify-center vh-100">
                    <h2 style="color: #FF6B6C; font-family: 'Kavoon'; font-weight: bold; font-size: 40px; padding: 20px; margin-top:50px;">Let's get started shall we?</h2>
                    <form action="{% url 'LoginRegister:register' %}" method="get">
                      <button class="btn btn-primary" type="submit" style="display: block; margin: 10px auto 0; font-size:26px;">Register</button>
                    </form>
                    <p class="register-link" style="color:#60AB9A; font-size:26px;">Already have an account? <a href="{% url 'LoginRegister:login' %}">Login</a></p>
                  </div>
              </div>
          </div>
        </div>
    </div>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

LoginRegister/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        body {
            background: url("{% static 'login_bg.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }
        
        .btn-primary {
            background-color: #FF6B6C;
            border-color: #FF5050;
            color: #fff;
            font-family: 'Kavoon';
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;
        }

        .form-control {
            background-color: #EEE5E5; 
            width: 100%;  
            border-radius: 4px;
            padding: 10px
        }
        
        .form-control::placeholder {
            color: #60AB9A;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center align-items-center vh-100">
            <div class="col-md-6">
                <div class="card bg-white shadow-lg p-4 rounded">
                    <h2 class="card-title text-center" style="color: #FF6B6C; font-family: 'Kavoon'; font-weight: bold; font-size: 70px; padding: 20px;">User Login</h2>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="username" id="username" placeholder="Username" class="form-control">
                        </div>
                        <div class="mb-3">
                            <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="text-center">
                            <button class="btn btn-primary" type="submit">LOGIN</button>
                        </div>
                    </form>
                    {% if messages %}
                        <div class="mt-4">
                            <ul class="list-group">
                                {% for message in messages %}
                                    <li class="list-group-item list-group-item-danger">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

LoginRegister/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>

        body {
            background: url("{% static 'register_bg.jpg' %}");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            border-radius: 8px;
            width: 100%;
            margin: 0 auto;
            padding: 20px;
            text-align: center;
            color: #fff; /* White text color */
        }
    
        .box {
            background-color: #FAEECE;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.3);
            width: 90%;
            margin: 0 auto;
            padding: 20px;
            text-align: center;
            color: #fff; /* White text color */
        }
    
        .form-control {
            width: 100%;
            padding: 15px;
            border-radius: 4px;
        }

        .form-control::placeholder {
            color: #60AB9A;
            font-weight: bold;
        }

        .messages {
            list-style: none;
            padding: 0;
            color: #ff0000; /* Red text color for messages */
        }

        label {
            color: gray;
        }
        .btn-primary {
            background-color: #FF6B6C;
            border-color: #FF5050;
            color: #fff;
            font-family: 'Kavoon';
        }

        @media (max-width: 768px) {
            .box {
                width: 100%;
                height: auto;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="box">
            <div class="row justify-content-center">
                <h1 class="card-title text-center" style="color: #FF6B6C; font-family: 'Kavoon'; font-weight: bold; font-size: 70px; padding: 20px;"> Create Your Account </h1>
                <div class="col-md-6">
                    <form method="POST" action="{% url 'LoginRegister:register' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" name="username" id="username" placeholder="Username" class="form-control">
                        </div>
                        <div class="mb-3">
                            <input type="password" name="password1" id="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="mb-3">
                            <input type="password" name="password2" id="confirm-password" placeholder="Confirm Password" class="form-control">
                            <span class="error-message" id="password-error"></span>
                        </div>
                        <div class="mb-3">
                            <label for="role">Select your role:</label>
                            <div>
                                <input type="checkbox" name="isGuru" id="isGuru">
                                <label for="isGuru">Teacher</label>
                            </div>
                        </div>
                        <div class="text-center">
                            <input class="btn btn-primary" type="submit" name="submit" value="CREATE"/>
                        </div>
                    </form>
                    
                    {% if messages %}
                        <div class="mt-4">
                            <ul class="list-group">
                                {% for message in messages %}
                                    <li class="list-group-item list-group-item-danger">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div> 
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('#confirm-password').on('input', function() {
                var password = $('#password').val();
                var confirmPassword = $(this).val();
                if (password !== confirmPassword) {
                    $('#password-error').text('Passwords do not match');
                } else {
                    $('#password-error').text('');
                }
            });
        });
    </script>
</body>
</html>