BookMates/urls.py
from django.contrib import admin
from django.urls import path, include
from LoginRegister import views
urlpatterns = [
    path('', include('LoginRegister.urls')),
    path('', views.show_home, name='home'),
    path('admin/', admin.site.urls),
    path('editbuku/', include('MengelolaBuku.urls')),
    path('searchbuku/', include('SearchKatalog.urls')),
    path('challenge/', include('ChallengeLeaderboard.urls')),
    path('',include('Dashboard.urls')),
    path('',include('Komunitas.urls')),
    path('leaderboard/', include('ReviewerLeaderboard.urls')),
    path('auth/', include('authentication.urls')),
    # path('api/books/', include("book.urls"))
]

MengelolaBuku/urls.py
from django.urls import path
from MengelolaBuku.views import show_book, add_book, get_books_json, get_books_json_id, remove_book
from MengelolaBuku.views import add_book_flutter, remove_book_flutter, show_book_flutter, get_pengguna_json

app_name = 'MengelolaBuku'

urlpatterns = [
    path('', show_book, name='show_book'),
    path('get-books-json/', get_books_json, name='get_books_json'),
    path('get-pengguna-json', get_pengguna_json, name='get_pengguna_json'),
    path('add-book', add_book, name='add_book'),
    path('get-books-json-id/<int:id>/', get_books_json_id, name='get_books_json_id'),
    path('remove_book/<int:id>/', remove_book, name='remove_book'),
    path('add-book-flutter/', add_book_flutter, name='add_book-flutter'),
    path('show-book-flutter/', show_book_flutter, name='show_book-flutter'),
    path('remove-book-flutter/', remove_book_flutter, name='remove_book_flutter')
]

MengelolaBuku/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pengguna(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    isGuru = models.BooleanField()
    point = models.IntegerField(default=0)
    banyak_review = models.IntegerField(default=0)
    banyak_bintang = models.IntegerField(default=0)

class Buku(models.Model):
    judul = models.CharField(max_length=500)
    author = models.CharField(max_length=500)
    rating = models.FloatField()
    num_of_rating = models.IntegerField()
    min_age = models.IntegerField()
    max_age = models.IntegerField()
    image_url = models.TextField()
    desc = models.TextField()
    user = models.ForeignKey(Pengguna, on_delete=models.CASCADE, blank=True, null=True)

MengelolaBuku/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from .models import Buku, Pengguna
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
import json
from django.contrib.auth.decorators import login_required

# Create your views here.
def show_book(request):
    if request.user.pengguna.isGuru == False:
        return redirect('dashboard:profile')

    books = Buku.objects.filter(user=Pengguna.objects.get(user=request.user))
    context = {
        books: books,
    }
    return render(request, 'show_book.html', context)

@csrf_exempt
def add_book(request):
    if request.user.pengguna.isGuru == False:
        return redirect('dashboard:profile')
    
    if request.method == 'POST':
        judul = request.POST.get("judul")
        author = request.POST.get("author")
        rating = request.POST.get("rating")
        num_of_rating = request.POST.get("num_of_rating")
        min_age = request.POST.get("min_age")
        max_age = request.POST.get("max_age")
        image_url = request.POST.get("url_image")
        description = request.POST.get("description")
        user = Pengguna.objects.get(user=request.user)

        new_product = Buku(judul=judul, author=author, rating=rating, 
                           num_of_rating=num_of_rating, min_age=min_age,
                           max_age=max_age, image_url=image_url, desc=description, user=user)
        new_product.save()
        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def get_books_json(request):
    buku_item = Buku.objects.all()
    return HttpResponse(serializers.serialize('json', buku_item), content_type="application/json")

def get_books_json_id(request, id):
    buku_item = Buku.objects.filter(pk=id)
    return HttpResponse(serializers.serialize('json', buku_item), content_type="application/json")

def remove_book(request, id):
    if Pengguna.objects.get(user=request.user).isGuru == False:
        return redirect('Dashboard:show_main')
    
    book = Buku.objects.get(pk=id)
    if (book.user == Pengguna.objects.get(user=request.user)):
        book.delete()
    return redirect('MengelolaBuku:show_book')

@csrf_exempt
def add_book_flutter(request):
    if request.method == 'POST':
        if Pengguna.objects.get(user=request.user).isGuru == False:
            return JsonResponse({"status": "forbidden"}, status=403)
        
        data = json.loads(request.body)

        new_product = Buku.objects.create(
            judul = data["judul"],
            author = data["author"],
            rating = 0,
            num_of_rating = 0,
            min_age = data["min_age"],
            max_age = data["max_age"],
            image_url = data["image_url"],
            desc = data["description"],
            user = Pengguna.objects.get(user=request.user)
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def remove_book_flutter(request):
    if Pengguna.objects.get(user=request.user).isGuru == False:
        return JsonResponse({"status": "error"}, status=403)
    
    data = json.loads(request.body)
    book = Buku.objects.get(pk=data["pk"])
    if (book.user == Pengguna.objects.get(user=request.user)):
        book.delete()
    return JsonResponse({"status": "success"}, status=200)

@csrf_exempt
def show_book_flutter(request):
    if Pengguna.objects.get(user=request.user).isGuru == False:
        return JsonResponse({"status": "error"}, status=403)

    books = Buku.objects.filter(user=Pengguna.objects.get(user=request.user))
    return JsonResponse(serializers.serialize('json', books), safe=False)

def get_pengguna_json(request):
    pengguna_objek = Pengguna.objects.all()
    return HttpResponse(serializers.serialize('json', pengguna_objek), content_type="application/json")

MengelolaBuku/templates/show_book.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'css/show_book.css' %}">
{% endblock meta %}

{% block title %}Show Book{% endblock %}

{% block content %}


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" id="header-modal">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add Book</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="judul" class="col-form-label">Book Title</label>
                      <input type="text" class="form-control" id="judul" name="judul" required></input>
                    </div>
                    <div class="mb-3">
                      <label for="author" class="col-form-label">Book Author</label>
                      <input type="text" class="form-control" id="author" name="author" required></input>
                    </div>
                    <div class="mb-3">
                      <label for="age" class="col-form-label">Recommended Age</label>
                      <input type="number" class="form-control" id="min_age" name="min_age" min="1" max="13" placeholder="from" required></input>
                      <input type="number" class="form-control" id="max_age" name="max_age" min="1" max="13" placeholder="until" required></input>
                    </div>
                    <label for="customRange3" class="form-label">Rating</label>
                    <input type="range" class="form-range" min="0" max="5" step="0.5" id="customRange3" value="3" oninput="updateValueDisplay()" required>
                    <label id="range-value-text">3</label>
                    <div class="mb-3">
                        <label for="edit-num-rating" class="col-form-label">Reviewed by</label>
                        <input type="number" class="form-control" id="edit-num-rating" name="edit-min-age" min="0" max="1000" placeholder="how many peopla left comment here?" required></input>
                    </div>
                    <div class="mb-3">
                      <label for="url_image" class="col-form-label">Book Cover Image URL</label>
                      <textarea class="form-control" id="url_image" name="url_image" required></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Synopsis</label>
                        <textarea class="form-control" id="description" name="description" required></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" id="detailModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header" id="header-modal">
          <h5 class="modal-title">Book Details</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="hideModal()"></button>
        </div>
        <div class="modal-body" id="details-modal-body">
          <p>Modal body text goes here.</p>
        </div>
      </div>
    </div>
</div>

<div class="wrapper-title">
    <h1 id="title">My Books</h1>
    <button id="add-book-button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add New Book</button>
</div>
<br>
<div id="wrapper-card" class="row row-cols-2 g-4"></div>


<script>
    async function getBooks() {
        return fetch("{% url 'MengelolaBuku:get_books_json' %}").then((res) => res.json())
    }

    async function getBooksId(objectId) {
        return fetch(`get-books-json-id/${objectId}`).then((res) => res.json())
    }

    async function refreshBooks() {
        document.getElementById("wrapper-card").innerHTML = ""
        const products = await getBooks()
        let htmlString = ""
        products.forEach((books) => {
            var book_rating = Math.round(books.fields.rating)
            var rating_kosong = 5 - book_rating
            var url_image = books.fields.image_url
            htmlString += `<div id="book-card" class="card col">
            <div class="card-body">
            <table>    
            <tr>
              <td rowspan="5"><img id="book-cover" src="${url_image}" alt="Book Cover"></td>
              <td colspan="2" id="title-wrapper"><h5 class="card-title">${books.fields.judul}</h5></td>
            </tr>
            <tr>
              <td colspan="2"><p class="card-text">Author:      ${books.fields.author}</p></td>
            </tr>
            <tr>
              <td colspan="2">       
                ${books.fields.max_age !== 99 ? `<p class="card-text">Age: ${books.fields.min_age}-${books.fields.max_age} years</p>` : `<p class="card-text">Age:         ${books.fields.min_age}+ years</p>`}
              </td>
            </tr>
            <tr>
              <td colspan="2">  
              <div class="ratings d-flex">
                <p class="card-text">${books.fields.rating}</p>
                <i class="fa fa-star rating-color"></i>
                <p class="card-text" style="margin-left: 20px;">(${books.fields.num_of_rating})</p>
              </div>
              </td>
            </tr>  
            <tr>
            <td><button class="btn btn-primary details-btn" id="details-button" onclick="showDetails(${books.pk})">Details</button></td>
            <td><a href="remove_book/{{item.pk}}/"><button class="btn remove-btn">🗑️</button></a></td>
            </tr>
            </table>
            </div>
            </div>` 
        })
        
        document.getElementById("wrapper-card").innerHTML = htmlString
    }
    
    refreshBooks()

    function addBook() {
        fetch("{% url 'MengelolaBuku:add_book' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addBook

    async function showDetails(objectId){
        document.getElementById("details-modal-body").innerHTML = ""
        let htmlString = ""
        var books = await getBooksId(objectId)
        books = books[0]
        console.log(books)
        var url_image = books.fields.image_url
        htmlString += `
        <table>    
            <tr>
              <td rowspan="5"><img id="book-cover" src="${url_image}" alt="Book Cover"></td>
              <td colspan="2" id="title-wrapper"><h5 class="card-title" style="margin-bottom: 10px;">${books.fields.judul}</h5></td>
            </tr>
            <tr>
              <td><p class="card-text" style="margin-bottom: 10px;"><b>Author</b></p></td>
              <td><p class="card-text" style="margin-bottom: 10px;">${books.fields.author}</p></td>
            </tr>
            <tr>
              <td>
              <p class="card-text" style="margin-bottom: 10px;"><b>Age</b></p></td>
              <td>
                ${books.fields.max_age !== 99 ? `<p class="card-text" style="margin-bottom: 10px;">${books.fields.min_age}-${books.fields.max_age} years</p>` : `<p class="card-text" style="margin-bottom: 10px;">${books.fields.min_age}+ years</p>`}
              </td>
            </tr>
            <tr>
                <td colspan="2"><p class="card-text" style="margin-bottom: 10px;">${books.fields.desc}</p></td>
            </tr>
            <tr>
              <td colspan="2">  
              <div class="ratings d-flex">
                <p class="card-text">${books.fields.rating}</p>
                <i class="fa fa-star rating-color"></i>
                <p class="card-text" style="margin-left: 20px;">(${books.fields.num_of_rating})</p>
              </div>
              </td>
            </tr>
        </table>`
        document.getElementById("details-modal-body").innerHTML = htmlString
        document.getElementById('detailModal').style.display = "block";

    }

    function hideModal(){
        document.getElementById('detailModal').style.display = 'none';
    }

    function updateValueDisplay() {
        var rangeInput = document.getElementById('customRange3');
        document.getElementById('range-value-text').textContent = rangeInput.value;
    }

    
</script>

{% endblock content %}