BookMates/urls.py
from django.contrib import admin
from django.urls import path, include
from LoginRegister import views
urlpatterns = [
    path('', include('LoginRegister.urls')),
    path('', views.show_home, name='home'),
    path('admin/', admin.site.urls),
    path('editbuku/', include('MengelolaBuku.urls')),
    path('searchbuku/', include('SearchKatalog.urls')),
    path('challenge/', include('ChallengeLeaderboard.urls')),
    path('',include('Dashboard.urls')),
    path('',include('Komunitas.urls')),
    path('leaderboard/', include('ReviewerLeaderboard.urls')),
    path('auth/', include('authentication.urls')),
    # path('api/books/', include("book.urls"))
]

ChallengeLeaderboard/urls.py
from django.urls import path
from . import views

app_name = 'ChallengeLeaderboard'

urlpatterns = [
    path('get_username/<int:pk>', views.get_username, name='get_username'),
    path('get_current_username/', views.get_current_username, name='get_username'),
    path('challenge/<str:name>', views.challenge, name='challenge'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('ranking/', views.get_ranking, name='get_ranking'),
    path('reviews/<str:book_pk>', views.get_reviews, name='get_reviews'),
    path('post_reviews', views.post_reviews, name='post_reviews'),
    path('get_reply/<str:challenge_name>', views.get_reply, name='get_reply'),
    path('post_reply/', views.post_reply, name='post_reply'),
    path('post_nilai/', views.post_nilai, name='post_nilai'),
    path('get_top10/<str:komunitas>', views.get_top10, name='get_top10'),
    path('get_rank/<str:komunitas>', views.get_rank, name='get_top10')
]

ChallengeLeaderboard/models.py
from django.db import models

from MengelolaBuku.models import Buku, Pengguna
from django.contrib.auth.models import User

from Komunitas.models import Community

# class Reply(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, unique=False)
#     text = models.TextField()
#     datetime = models.DateTimeField()
#     point = models.IntegerField(default=0)

#     def __str__(self) -> str:
#         return self.user.username +" : "+ self.text

class Reviews(models.Model):
    buku = models.ForeignKey(Buku, on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(Pengguna, on_delete=models.CASCADE, null=False)
    text = models.TextField()
    rating = models.FloatField()

class NewReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    point = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.user.username +" : "+ self.text
    
class Challenge(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE, null=False)
    name = models.TextField(primary_key=True)
    point = models.IntegerField()
    deadline = models.DateTimeField()
    description = models.TextField()
    book = models.ForeignKey(Buku, on_delete=models.CASCADE)
    reply = models.ManyToManyField(NewReply, blank=True)

    def __str__(self) -> str:
        return self.name
    

ChallengeLeaderboard/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, HttpResponseBadRequest, JsonResponse

from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
import json
import datetime

from . import models
from MengelolaBuku.models import Pengguna, Buku, User

USERNAME = 'root'

@csrf_exempt
def get_username(request, pk: int):
    user = Pengguna.objects.get(pk=pk)
    return JsonResponse(json.dumps({'username': user.user.username}), safe=False, status=200)

@csrf_exempt
def get_current_username(request):
    user = request.user
    return JsonResponse(json.dumps({'username': user.username}), safe=False, status=200)

# NEW ENDPOINT 
def get_ranking(request):
    """
        Return JSON list contains Nama, banyak yang direview, status, banyak bintang total
    """
    all_pengguna = Pengguna.objects.all()
    return JsonResponse(serializers.serialize('json', all_pengguna), safe=False)

@csrf_exempt
def get_reviews(request, book_pk:str):
    """
        Return JSON list of reviews
    """
    buku = Buku.objects.get(pk=book_pk)
    all_reviews = models.Reviews.objects.filter(buku=buku)
    return JsonResponse(serializers.serialize('json', all_reviews), safe=False)

@csrf_exempt
def post_reviews(request):
    """
        Body:
            pk: pk a book
            text: review's  text
            rating: int [1, 5] of rating
    """
    try:
        data = json.loads(request.body)

        pk = int(data['pk'])
        text = data['text']
        rating = float(data['rating'])
        user = Pengguna.objects.get(user=request.user)

        buku = Buku.objects.get(pk=pk)
        new_review = models.Reviews.objects.create(buku=buku, user=user, text=text, rating=rating).save()

        user.banyak_bintang += rating
        user.banyak_review += 1
        user.save(update_fields=['banyak_bintang', 'banyak_review'])
        return JsonResponse({'status': 'ok'}, status=200)
    except ValueError as e:
        print(e)
        return JsonResponse({'status': 'error'}, status=401)

########################

def leaderboard(request):
    # TODO: CONFIGURE SET USER 
    user = models.User.objects.get(username=USERNAME)

    komunitas_joined = []
    for komunitas in models.Community.objects.all():
        if user in komunitas.members.all():
            komunitas_joined.append(komunitas)

    context = {
        'komunities' : komunitas_joined,
        'user' : user
    }
    return render(request, 'leaderboard.html', context=context)

@csrf_exempt
def get_rank(request, komunitas):
    # TODO: CONFIGURE USERNAME
    # username = request.user.username
    username = USERNAME

    komunitas = models.Community.objects.get(name=komunitas)
    pengguna_all = [Pengguna.objects.get(user=user) for user in komunitas.members.all()]
    pengguna_point = sorted([(pengguna, pengguna.point) for pengguna in pengguna_all], key=lambda x: x[1], reverse=True)
    for position, (pengguna, point) in enumerate(pengguna_point):
        if pengguna.user.username == username:
            return JsonResponse({'position': position+1, 'name': username, 'point': point})
    return JsonResponse({'position': '-', 'name': username, 'point': 0})

@csrf_exempt
def get_top10(request, komunitas):
    komunitas = models.Community.objects.get(name=komunitas)
    member_point = []
    for member in komunitas.members.all():
        pengguna = Pengguna.objects.get(user=member)
        member_point.append((member, pengguna.point))
    member_point = sorted(member_point, key=lambda x: x[1], reverse=True)
    data = [{'name': member.username, 'point': point} for member, point in member_point]

    return JsonResponse(data, safe=False)  # Use JsonResponse to return JSON data

@csrf_exempt
def get_teacher(request):
    # TODO
    komunitas_name = request.GET.get('komunitas')
    komunitas = models.Community.objects.get(name=komunitas_name)
    return HttpResponseNotFound("Page not Implemented")

@csrf_exempt
def get_reply(request, challenge_name: str):
    challenge = _get_or_404(models.Challenge, name=challenge_name)
    if type(challenge) is HttpResponseNotFound:
        return challenge

    dct = []
    print('CHALLENGE', challenge, challenge.reply.all())
    for reply in challenge.reply.all():
        dct.append({
            'user': reply.user.username,
            'text': reply.text,
            'point': reply.point
        })

    return JsonResponse(dct, safe=False)


@csrf_exempt
def post_nilai(request):
    if request.method != 'POST' or request.POST.get('user') is None or request.POST.get('value') is None or request.POST.get('challenge_name') is None:
        return HttpResponseBadRequest('Not a Valid request')
    username = request.POST.get('user')
    new_point = request.POST.get('value')
    challenge_name = request.POST.get('challenge_name')

    print(f'EDIT NILAI REQUEST on {username}')
    user = models.User.objects.get(username=username)
    pengguna = Pengguna.objects.get(user=user)
    reply = models.Challenge(name=challenge_name).reply
    myReply = reply.get(user=user)

    old_point = myReply.point
    myReply.point = new_point
    myReply.save(update_fields=['point'])

    pengguna.point -= old_point
    pengguna.point += int(new_point)
    pengguna.save(update_fields=['point'])

    return HttpResponse(f"Old Point {old_point}, New Point {myReply.point}, Pengguna Point {pengguna.point}")

@csrf_exempt
def post_reply(request):
    challenge_name = request.POST.get('challenge_name')
    text = request.POST.get('text')
    # TODO: CONFIGURE USERNAME
    # user = request.user
    user = models.User.objects.get(username=USERNAME)

    print("DATA SUBMITTED : ", challenge_name, text)

    challenge: models.Challenge = _get_or_404(models.Challenge, name=challenge_name)
    if type(challenge) is HttpResponseNotFound:
        return challenge
    
    print('Halo halo')
    my_reply, created = models.NewReply.objects.get_or_create(user=user, text=text, point= 0)
    print('CREATED', created)

    if created:
        challenge.reply.add(my_reply)
    else:
        my_reply.text = text
        my_reply.save(update_fields=['text'])

        if my_reply not in challenge.reply.all():
            challenge.reply.add(my_reply)
    

    return HttpResponse("OK")

def challenge(request, name: str):
    challenge: models.Challenge = _get_or_404(models.Challenge, name=name)
    if type(challenge) is HttpResponseNotFound:
        return challenge
    
    # TODO: CONFIGURE SET USER 
    # request.user
    user = models.User.objects.get(username=USERNAME)
    
    isreply = _get_or_404(challenge.reply, user=user)
    isreply = None if type(isreply) is HttpResponseNotFound else isreply

    isguru = Pengguna.objects.get(user=user).isGuru

    context = dict(
        name = challenge.name,
        datetime = challenge.deadline.strftime("%B %d, %Y %H:%M"),
        point = challenge.point,
        description = challenge.description,
        book = challenge.book,
        showReply = not isreply,
        isguru = isguru
    )
    return render(request, 'challenge.html', context=context)


#################### HELPER FUNCTION ####################
def _get_or_404(model, **kwargs):
    try:
        if hasattr(model, 'objects'):
            data = model.objects.get(**kwargs)
        elif hasattr(model, 'get'):
            data = model.get(**kwargs)
        else:
            raise NotImplementedError('Model type not implemented')
    except Exception as e:
        return HttpResponseNotFound()
    return HttpResponseNotFound() if data is None else data

ChallengeLeaderboard/templates/challenge.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <style>
        body {
            background-image: url({% static "challenge_background.png" %});
            background-repeat: no-repeat;
            background-size: cover;
        }
        .rating-color{
            color: #FBC634 !important;
        }
        .text{
            font-family: 'Inter';
            font-style: normal;
        }
        .title{
            font-family: 'Kavoon';
            font-style: normal;
        }
    </style>
    <script>
        async function fetch_reply(){
            return fetch("{% url 'ChallengeLeaderboard:get_reply' name %}")
                .then(
                    (data) => data.json()
                )
        }
        async function on_jawaban_submit(event){
            event.preventDefault();
            const data = new FormData();
            text = document.getElementById("reply_text_area").value
            data.append('text', text)
            data.append('challenge_name', "{{ name }}")

            fetch("{% url 'ChallengeLeaderboard:post_reply'%}",{
                method: 'POST',
                body: data,
            }).then(
                (data) => {
                    alert("Jawaban Telah Dikirim!")
                    location.reload()
                }
            )
        }
        async function getBooksId(objectId) {
            return fetch(`../editbuku/get-books-json-id/${objectId}`).then((res) => res.json())
        }
        function hideModal(){
            document.getElementById('detailModal').style.display = 'none';
        }
        async function showDetails(objectId){
            document.getElementById("details-modal-body").innerHTML = ""
            let htmlString = ""
            var books = await getBooksId(objectId)
            books = books[0]
            var url_image = books.fields.image_url
            htmlString += `
            <table>    
                <tr>
                  <td rowspan="5"><img id="book-cover" src="${url_image}" alt="Book Cover"></td>
                  <td colspan="2" id="title-wrapper"><h5 class="card-title">${books.fields.judul}</h5></td>
                </tr>
                <tr>
                  <td><p class="card-text"><b>Author</b></p></td>
                  <td><p class="card-text">${books.fields.author}</p></td>
                </tr>
                <tr>
                  <td>
                  <p class="card-text"><b>Age</b></p></td>
                  <td><p class="card-text">${books.fields.min_age}-${books.fields.max_age} years</p></td>
                </tr>
                <tr>
                    <td colspan="2><p class="card-text">${books.fields.desc}</p></td>
                </tr>
                <tr>
                  <td colspan="2">  
                  <div class="ratings d-flex">
                    <p class="card-text">${books.fields.rating}</p>
                    <i class="fa fa-star" style="color: #FBC634 !important;"></i>
                    <p class="card-text" style="margin-left: 20px;">(${books.fields.num_of_rating})</p>
                  </div>
                  </td>
                </tr>
            </table>`
            document.getElementById("details-modal-body").innerHTML = htmlString
            document.getElementById('detailModal').style.display = "block";
        }
        async function onNilaiChange(new_value, user, challenge_name){
            if (new_value < 0) {
                new_value = 0
                alert("Nilai Tidak Boleh Negatif!")
            }else if(new_value > {{ point| safe }}){
                new_value = {{ point| safe }}
                alert("Nilai Melebihi Point Challenge Maksimal!")
            }
            const data = new FormData();
            data.append('user', user);
            data.append('value', new_value);
            data.append('challenge_name', challenge_name);

            document.getElementById(`pointInput-${user}`).value = new_value

            fetch("{% url 'ChallengeLeaderboard:post_nilai' %}", {
                method: 'POST',
                body: data,
            })
        }
        async function showReply(){
            data = await fetch_reply()
            text = document.getElementById("reply").innerHTML
            for(index in data){
                {% if isguru %}
                    text += `<div class="m-4 p-3 rounded" style="background-color: #F8DCE2;">
                        <div class="d-flex justify-content-between align-items-center">
                            <h4 class="title">${data[index].user}</h4>
                            <form class="form-floating" action="javascript:void(0);">
                                <input type="number" class="form-control title" id="pointInput-${data[index].user}" value="${data[index].point}">
                                <label class="text" for="pointInput">Nilai ${data[index].user}</label>
                            </form>
                        </div>
                        <p class="text">${data[index].text}</p>
                    </div>`
                {% else %}
                    text += `<div class="m-4 p-3 rounded" style="background-color: #F8DCE2;">
                        <div class="d-flex justify-content-between align-items-center">
                            <h4>${data[index].user}</h4>
                            <form class="form-floating" action="javascript:void(0);">
                                <input type="number" class="form-control" id="pointInput-${data[index].user}" value="${data[index].point}" disabled>
                                <label for="pointInput">Nilai ${data[index].user}</label>
                            </form>
                        </div>
                        <p>${data[index].text}</p>
                    </div>`
                {% endif %}
            }
            document.getElementById("reply").innerHTML = text
            for(index in data){
                console.log(data[index].user)
                document.getElementById(`pointInput-${data[index].user}`).addEventListener('change',
                    (value) => onNilaiChange(value.target.value, data[index].user, "{{name}}")
                )
            }
        }
        window.onload = async function(e){ 
            showReply()
        }
    </script>
    <div class="py-5"/>
    <div class="container">
        <div class="d-flex">
            <img src="{% static "task.png" %}" height="80" width="80">
            <div class="container mx-2">
                <h1 class="py-0 my-0 title"> {{name}} </h1>
                <p class="py-0 my-0 text"> {{datetime}} ({{point}} point) </p>
                <hr class="my-1 py-0" style="border: 3px solid black; border-radius: 5px;"/>
                <p class="lh-1 text">{{description}}</p>
                <div class="my-1 p-3 rounded" style="background-color: #FBDCE2;">
                    <div class="d-flex">
                        <img id="book-cover" src={{book.image_url}} alt="Book Cover" style="height:10%; width:10%;">
                        <div class="mx-4">
                            <h5 class="title">{{book.judul}}</h5>
                            <p class="py-0 my-0 text">Author {{book.author}}</p>
                            <p class="py-0 my-0 text">Age {{book.min_age}}-{{book.max_age}} years</p>
                            <div class="ratings d-flex py-0 my-0">
                                <p class="my-auto text">{{book.rating}}</p>
                                <i class="fa fa-star rating-color my-auto"></i>
                                <p class="text-center my-auto text">({{book.num_of_rating}})</p>
                            </div>
                                <button class="btn btn-primary details-btn text" id="details-button" onclick="showDetails({{book.pk}})">Details</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rounded my-3 " style="background-color: #FF6B6C;">
                <div class="mx-3 py-3 d-flex align-items-center">
                    <img src="{% static "checklist.png" %}" height="70" width="70">
                    <h1 class="text-center title">Pengumpulan</h1>
                </div>
                <div id="reply">
                    {% if showReply %}
                    <div class="m-4 p-3 rounded" style="background-color: #F8DCE2;">
                        <h4>Jawaban Kamu</h4>
                        <form onsubmit="on_jawaban_submit(event); return false;">
                            <div class="form-floating">
                                <textarea class="form-control" placeholder="Leave a comment here" name="reply" id="reply_text_area"></textarea>
                                <label for="floatingTextarea">Kamu belum mengirim jawaban...</label>
                            </div>
                            <input class="form-control mt-3 btn btn-primary fw-bold" type="submit" value="Kirim Jawaban!">
                        </form>
                    </div>
                    {% endif %}
                </div>
                <div class="py-3">
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="detailModal">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header" id="header-modal">
              <h5 class="modal-title">Book Details</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="hideModal()"></button>
            </div>
            <div class="modal-body" id="details-modal-body">
              <p>Modal body text goes here.</p>
            </div>
          </div>
        </div>
    </div>
{% endblock content %}

ChallengeLeaderboard/templates/leaderboard.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Challenge</title>
{% endblock meta %}

{% block content %}
    <style>
        body {
            background-image: url({% static "leaderboard_background.png" %});
            background-repeat: no-repeat;   
            background-size: cover;
        }
        .text{
            font-family: 'Inter';
            font-style: normal;
            font-size: large;
        }
        .title{
            font-family: 'Kavoon';
            font-style: normal;
        }
    </style>
</head>
<body>
    <script>
        async function onKomunitasChange(komunitas) {
            if(komunitas == '--'){
                document.getElementById("user_rank").innerHTML = '-'
                document.getElementById("user_username").innerHTML = "{{user.username}}"
                document.getElementById("user_point").innerHTML = '-'
                document.getElementById("leaderboard table").innerHTML = ""
                return;
            }
            fetch(`../get_top10/${komunitas}`).then(
                (data) => data.json()
            ).then(
                (data) => {
                    text = ""
                    for(index in data){
                        text += `<tr>
                            <td class="px-4">${parseInt(index)+1}</td>
                            <td class="px-4 text">${data[index].name}</td>
                            <td class="text-end px-4">
                                <img src="{% static "point.png" %}" width="3%">
                                ${data[index].point}
                            </td>
                        </tr>`
                        index += 1;
                    }
                    document.getElementById("leaderboard table").innerHTML = text
                }
            )

            fetch(`../get_rank/${komunitas}`).then(
                (data) => data.json()
            ).then(
                (data) => {
                    document.getElementById("user_rank").innerHTML = data.position
                    document.getElementById("user_username").innerHTML = data.name
                    document.getElementById("user_point").innerHTML = data.point
                }
            )
        }
        window.onload = async function (e){
            document.getElementById("komunitasSelect").onchange = function() {
                var selectedValue = this.value;
                onKomunitasChange(selectedValue);
            };
            
        }
    </script>
    <div class="m-4 justify-content-center">
        <div class="container text-center my-4">
            <h1 class="fw-bold title">Leaderboard</h1>
            <p class="my-4 text">Selamat datang di halaman Leaderboard! Di sini, kamu dapat melihat peringkat kamu pada komunitas kamu berdasarkan nilai yang diperoleh dari tantangan. Leaderboard dirancang untuk mendorong semangat kompetitif yang sehat dan memotivasi siswa untuk terus belajar dan berkembang. Mari kita lihat siapa yang berada di puncak!</p>
            <div class="container" style="width: 30%">
                <img src="{% static "medals.png" %}" class="img-fluid"/>
            </div>
        </div>
        <div class="container align-items-center w-75" style="display: flex;">
            <div class="form-floating w-75">
                <select class="form-select" id="komunitasSelect" aria-label="Floating label select example">
                    <option selected> -- </option>
                    {% for komunitas in komunities %}
                        <option value="{{komunitas.name}}">{{komunitas.name}}</option>
                    {% endfor %}
                </select>
                <label for="komunitasSelect">Lihat Komunitas</label>
            </div>
            <div class="form-floating w-25 ms-4">
                <select class="form-select" id="guruSelected" aria-label="Floating label select example" disabled>
                    <option selected> -- </option>
                </select>
                <label for="guruSelected">Guru</label>
            </div>
        </div>
        <div class="container text-center my-3">
            <h5 class="fw-bold title">Peringkat Kamu</h5>
        </div>
        <div class="container align-items-center w-75 my-4">
            <table class="table text-center align-items-center rounded-3 overflow-hidden">
                <thead></thead>
                <tbody class="text-center">
                    <tr>
                        <td class="px-4" id="user_rank">-</td>
                        <td class="px-4 text" id="user_username">{{user.username}}</td>
                        <td class="text-end px-4">
                            <img src="{% static "point.png" %}" width="4%">
                            <span id="user_point">-</span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div class="container text-center my-4">
            <h5 class="fw-bold title">Top 10 Terbaik</h5>
        </div>
        <div class="text-center rounded-3 overflow-hidden">
            {% for komunitas in komunities %}
                <div class="container align-items-center w-75 my-2">
                    <table class="table text-center align-items-center rounded-3 overflow-hidden">
                        <thead></thead>
                        <tbody class="text-center" id="leaderboard table">            
                        </tbody>
                    </table>
                </div>
            {% endfor %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>
{% endblock content %}